name: Deploy Movie Store Infrastructure

on:
  workflow_dispatch:
    
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Sign into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Lint Bicep
        uses: Azure/cli@v1
        with:
          inlineScript: |
            az bicep build --file ./deploy/main.bicep
  validate:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sign into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get existing images
        id: getimages
        run: |
          echo "Installing containerapp extension"
          az extension add -n containerapp --yes
          webImage=$(az containerapp show --name movie-web --resource-group ${{ secrets.AZURE_RG }} --query "properties.template.containers[0].image" -o tsv)
          catalogImage=$(az containerapp show --name movie-catalog --resource-group ${{ secrets.AZURE_RG }} --query "properties.template.containers[0].image" -o tsv)          
          echo "::set-output name=catalogImage::$catalogImage"
          echo "::set-output name=webImage::$webImage"

      - name: Run preflight validation
        uses: azure/arm-deploy@v1
        with:
          deploymentName: ${{ github.run_number }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./deploy/main.bicep
          deploymentMode: Validate
          parameters: sqlAdminUsername=${{ secrets.SQL_USERNAME }} sqlAdmin=${{ secrets.SQL_PASSWORD }} catalogApiImage=${{ steps.getimages.outputs.catalogImage }} webAppImage=${{ steps.getimages.outputs.webImage }}

  preview:
    needs: [lint, validate]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        name: Sign into Azure
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get existing images
        id: getimages
        run: |
          echo "Installing containerapp extension"
          az extension add -n containerapp --yes
          webImage=$(az containerapp show --name movie-web --resource-group ${{ secrets.AZURE_RG }} --query "properties.template.containers[0].image" -o tsv)
          catalogImage=$(az containerapp show --name movie-catalog --resource-group ${{ secrets.AZURE_RG }} --query "properties.template.containers[0].image" -o tsv)          
          echo "::set-output name=catalogImage::$catalogImage"
          echo "::set-output name=webImage::$webImage"
      
      - uses: Azure/cli@v1
        name: Run what-if
        with:
          inlineScript: |
            az deployment group what-if --resource-group ${{ secrets.AZURE_RG }} --template-file ./deploy/main.bicep --parameters sqlAdminUsername=${{ secrets.SQL_USERNAME }} sqlAdmin=${{ secrets.SQL_PASSWORD }} catalogApiImage=${{ steps.getimages.outputs.catalogImage }} webAppImage=${{ steps.getimages.outputs.webImage }}
  
  deploy-infra:
    runs-on: ubuntu-latest
    environment: Production
    needs: preview
    steps:
      - uses: actions/checkout@v2

      - name: Sign into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get existing images
        id: getimages
        run: |
          echo "Installing containerapp extension"
          az extension add -n containerapp --yes
          webImage=$(az containerapp show --name movie-web --resource-group ${{ secrets.AZURE_RG }} --query "properties.template.containers[0].image" -o tsv)
          catalogImage=$(az containerapp show --name movie-catalog --resource-group ${{ secrets.AZURE_RG }} --query "properties.template.containers[0].image" -o tsv)          
          echo "::set-output name=catalogImage::$catalogImage"
          echo "::set-output name=webImage::$webImage"

      - name: Deploy Bicep Template
        uses: azure/arm-deploy@v1
        with:
          deploymentName: ${{ github.run_number }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./deploy/main.bicep
          deploymentMode: Incremental
          parameters: sqlAdminUsername=${{ secrets.SQL_USERNAME }} sqlAdmin=${{ secrets.SQL_PASSWORD }} catalogApiImage=${{ steps.getimages.outputs.catalogImage }} webAppImage=${{ steps.getimages.outputs.webImage }}